import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — PRAVÉ",
  description: "How PRAVÉ collects, uses, and protects your personal information.",
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#070A12] px-6 py-16 text-white">
      <div className="mx-auto max-w-3xl">
        <div className="mb-2 text-sm font-semibold uppercase tracking-[0.2em] text-white/40">
          Legal
        </div>
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Privacy Policy</h1>
        <p className="mt-3 text-sm text-white/50">Last updated: April 2025</p>

        <div className="mt-10 space-y-8 text-sm leading-7 text-white/72">
          <section>
            <h2 className="mb-3 text-base font-semibold text-white">1. Information We Collect</h2>
            <p>
              When you use PRAVÉ, we collect information you provide directly — such as your email
              address when you sign up or submit a lead form — and information generated by your
              use of the simulator, including CRS profile inputs and saved roadmap data.
            </p>
            <p className="mt-3">
              We also collect standard usage data (pages visited, session duration, browser type)
              via analytics tooling to understand how the product is used.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">2. How We Use Your Information</h2>
            <ul className="list-disc space-y-2 pl-5">
              <li>To provide, maintain, and improve the CRS simulator and roadmap service.</li>
              <li>To authenticate your account and associate saved roadmaps with your profile.</li>
              <li>To process payments securely via Stripe.</li>
              <li>To send transactional emails (account confirmation, receipts) via Resend.</li>
              <li>To analyze aggregate usage patterns and improve the product experience.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">3. Data Storage and Security</h2>
            <p>
              Your data is stored in Supabase (PostgreSQL), hosted in secure cloud infrastructure.
              Passwords are never stored — authentication is handled via magic links or OAuth.
              Payment information is processed entirely by Stripe and never stored on our servers.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">4. Third-Party Services</h2>
            <p>We use the following third-party services, each governed by their own privacy policies:</p>
            <ul className="mt-3 list-disc space-y-2 pl-5">
              <li>
                <strong className="text-white">Supabase</strong> — database and authentication
              </li>
              <li>
                <strong className="text-white">Stripe</strong> — payment processing
              </li>
              <li>
                <strong className="text-white">OpenAI</strong> — AI strategy generation
              </li>
              <li>
                <strong className="text-white">Resend</strong> — transactional email
              </li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">5. Data Retention and Deletion</h2>
            <p>
              You may request deletion of your account and associated data at any time by contacting
              us. We will remove your personal data within 30 days of a confirmed deletion request,
              except where retention is required by law.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">6. Your Rights (PIPEDA / CASL)</h2>
            <p>
              As a Canadian-based service, we comply with PIPEDA. You have the right to access,
              correct, or request deletion of your personal information. You may also withdraw
              consent to marketing communications at any time by contacting us.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">7. Contact</h2>
            <p>
              For privacy-related questions or requests, contact us at{" "}
              <span className="text-white">privacy@prave.ca</span>.
            </p>
          </section>
        </div>

        <div className="mt-12 flex flex-wrap gap-4 border-t border-white/10 pt-8 text-sm text-white/45">
          <Link href="/terms" className="transition hover:text-white">
            Terms of Service
          </Link>
          <Link href="/" className="transition hover:text-white">
            Back to Home
          </Link>
        </div>
      </div>
    </main>
  );
}
